Repository albumentations-team/albumentations, pull requests merged in 2022-07, with the labels that each got.

#1207 Fix contrast mean value for float32 and factor=0
  albumentations/augmentations/functional.py
Labels: Awaiting merge

#1218 Speedup tests
  tests/conftest.py
  tests/test_imgaug.py
  tests/test_random.py
  tests/test_transforms.py
Labels: Awaiting merge, Speed Improvements

#1091 Fix Affine wrong rotation angle
  albumentations/augmentations/geometric/functional.py
  albumentations/augmentations/geometric/transforms.py
  tests/test_functional.py
  tests/test_keypoint.py
  tests/test_transforms.py
Labels: Awaiting merge

#563 Normalize using cv2
  albumentations/augmentations/functional.py
  tests/test_functional.py
Labels: Awaiting merge

#487 Fix _brightness_contrast_adjust_uint when beta_by_max = False
  albumentations/augmentations/functional.py
  tests/test_functional.py
Labels: Need more info, Branch conflict

#1231 Fix Affine and Perspective bbox clipping
  albumentations/augmentations/geometric/functional.py
  tests/test_transforms.py
Labels: Bugfix

#616 Fix #615 bboxes with min_visibility are excluded
  albumentations/augmentations/dropout/channel_dropout.py
  albumentations/augmentations/dropout/cutout.py
  albumentations/augmentations/dropout/functional.py
  albumentations/augmentations/dropout/grid_dropout.py
  albumentations/core/bbox_utils.py
  tests/test_bbox.py
Labels: Branch conflict

#476 Added transform "RandomCropFromBorders" and support for BBox in ElasticTransform, GridDistortion, OpticalDistortion
  README.md
  albumentations/augmentations/functional.py
  albumentations/augmentations/transforms.py
Labels: Awaiting merge
