Repository albumentations-team/albumentations, pull requests merged in 2022-06, with the labels that each got.

#1109 Fix safe rotate targets
  albumentations/augmentations/geometric/functional.py
  albumentations/augmentations/geometric/rotate.py
  albumentations/augmentations/keypoints_utils.py
  tests/test_transforms.py
Labels: Awaiting merge

#1059 Fix crop_and_pad_bbox
  albumentations/augmentations/crops/functional.py
  tests/test_imgaug.py
Labels: Need more info, Awaiting merge

#1104 Add keep ratio flag to Affine transform
  albumentations/augmentations/geometric/transforms.py
  tests/test_transforms.py
Labels: Awaiting merge

#1102 Fix bug in RingingOvershoot transform
  albumentations/augmentations/transforms.py
Labels: Awaiting merge

#1080 Corrected off-by-one in random crop.
  albumentations/augmentations/crops/functional.py
  tests/files/output_v1.1.0_with_totensor.json
  tests/files/output_v1.1.0_without_totensor.json
  tests/test_functional.py
Labels: Need more info

#1189 Bump version to 1.2.0
  albumentations/__init__.py
Labels: Awaiting merge

#1159 Docs: Affine - improve `fit_output` documentation
  albumentations/augmentations/geometric/transforms.py
Labels: Awaiting merge

#1121 Fix a deprecation warning in match_histograms
  albumentations/augmentations/domain_adaptation.py
  setup.py
Labels: wontfix
